### PR TITLE
Fix bug where --config always failed with --resolve-bare-modules error

### PR DESCRIPTION
**Pull request by aomarks**

### CODE REVIEW

**Comment by aomarks** [comment]
> Why does this fix the issue with --config?

Because after flag parsing, when there is a config file, we error if the user specified any flags that are already handled by a config file. Probably too strict, but I didn't want to deal with the ambiguity when they conflict: https://github.com/Polymer/tachometer/blob/master/src/cli.ts#L120

If there's a default in the CLI arg configuration, then you can't tell the difference between unspecified and specified to the same value as the default. Then we apply defaults after the check.

**Comment by rictic** [comment]
Does `--resolve-bare-modules` still default to true both with `--config` and without it? Were we double-specifying its default value?

**Comment by aomarks** [comment]
> Does `--resolve-bare-modules` still default to true both with `--config` and without it? Were we double-specifying its default value?

Yes and yes https://github.com/Polymer/tachometer/blob/master/src/cli.ts#L149

**Comment by aomarks** [comment]
> Yes and yes https://github.com/Polymer/tachometer/blob/master/src/cli.ts#L149

(that's the default when not using config, here's where the default when it is https://github.com/Polymer/tachometer/blob/master/src/config.ts#L279)

(I want to refactor this where both modes do something like return a partial config object, and then there's a single function that applies the defaults.)

**Pull request merged**
